[package]
name = "lend_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]


[build-dependencies]
candid = "0.7.10"

[dependencies]
candid = "0.7.10"
ic-cdk = "0.3.3"
ic-cdk-macros = "0.3.3"
ic-ledger-types = "0.1.0"
ic-types = "0.2.1"
num-bigint = "0.4"
num-traits = "0.2.14"
serde = "1.0.126"
serde_derive = "1.0.126"